Repository thinkbig-project/thinkbig, pull requests merged in 2023-12, with the labels that each got.

#15 Solution for the issue #4.
  app/page.tsx
  package-lock.json
Labels: frontend

#34 32 update frontpage style
  app/components/ui/Avatar.tsx
  app/page.tsx
  package-lock.json
  public/footerbg.svg
  tailwind.config.ts
Labels: frontend, html/css, tailwind, typescript

#37 36 create protected dashboard page
  app/api/auth/[...nextauth]/route.ts
  app/dashboard/page.tsx
  app/page.tsx
  app/users/[id]/route.ts
  app/users/route.ts
  package.json
  pnpm-lock.yaml
  repo.zip
Labels: frontend, tailwind, typescript, mongo/prisma
