Repository thinkbig-project/thinkbig, pull requests merged in 2024-01, with the labels that each got.

#43 #41 create tag component
  app/components/ui/Tag.tsx
Labels: frontend, typescript

#57 #48 create `middleware.ts`
  middleware.ts
Labels: data structure, typescript, nextjs/react

#59 38 create card component
  .env.example
  app/components/ui/Avatar.tsx
  app/components/ui/Card.tsx
  app/components/ui/CrudButton.tsx
  app/components/ui/IssueIcon.tsx
  app/dashboard/page.tsx
  app/page.tsx
  next.config.js
  public/placeholder.png
  repo.zip
Labels: frontend, tailwind, typescript, nextjs/react

#64 50 create a modal component
  app/components/ui/Modal.tsx
  app/globals.css
Labels: frontend, tailwind, typescript, nextjs/react

#65 52 create an input component
  app/components/parallax/EmojiParallaxContainer.tsx
  app/components/parallax/EmojiParallaxItem.tsx
  app/components/ui/Button.tsx
  app/components/ui/CloseButton.tsx
  app/components/ui/Dropdown.tsx
  app/components/ui/Input.tsx
  app/dashboard/page.tsx
  app/page.tsx
  types/EmojiParallaxContainerProps.ts
  types/InputProps.ts
  types/index.ts
Labels: frontend, tailwind, typescript, nextjs/react

#69 60 create a sidenav component
  app/components/nav/SideNav.tsx
  app/dashboard/layout.tsx
  app/page.tsx
  tailwind.config.ts
Labels: good first issue, frontend, tailwind, typescript, nextjs/react

#74 changed nested [id] in app api routes to [slug]
  app/api/users/[id]/issues/[slug]/route.ts
  app/api/users/[id]/route.ts
Labels: bug, typescript, nextjs/react
